### ISSUE TITLE
Programs are being installed under the current user profile with system wide variables set to those directories

### ISSUE THREAD

**Issue by dmssargent** [JacobAMason/FTCDevSuite#11]
System variables should not be set to directories within a current user directory. This requires an local administrator (or higher) to access the location in the variable creating a problem with computers with multiple users using the FTC Software.

Possible resolutions:
1. Install the affected software in a location accessible by all users and keep the variable code the same.
2. Keep the affected software being installed in the same place and alter the variable code to create system variables in the scope of the current user [HKEY_CURRENT_USER\Environment]

**Comment by JacobAMason** [comment]
The only tool I see affected by this is Ant. Is that correct or are there others?

**Comment by dmssargent** [comment]
I only saw Ant being affected at this problem at this point.
