### ISSUE TITLE
Android Studio 2.1.2

### ISSUE THREAD

**Issue by JacobAMason** [JacobAMason/FTCDevSuite#13]
Android Studio 1.5.1 has a security hole of some sort. We should install the latest version of Android Studio.

**Comment by dmssargent** [comment]
Android Studio 2.1.2 requires JDK 8, instead of JDK 7. https://developer.android.com/studio/index.html#downloads (scroll up a bit)

**Comment by JacobAMason** [comment]
Indeed. I'll probably change out the version because I've used 8 forever and have never had any issues.

**Comment by ftctechnh** [comment]
@JacobAMason 

We are moving the ftc_app project to support Android Studio 2.1.x.  We released a mini "beta" branch with the only change being that gradle files were modified to support Android Studio 2.1.x.

https://github.com/ftctechnh/ftc_app/tree/beta

**Comment by JacobAMason** [comment]
@ftctechnh I'm glad you said that, I was trying to figure out how I'd modify the Gradle files myself during the installation, but this should make it much nicer.
