### ISSUE TITLE
Java JDK gets reinstalled, if the JDK is currently installed

### ISSUE THREAD

**Issue by dmssargent** [JacobAMason/FTCDevSuite#15]
The Java JDK is getting reinstalled, even though the JDK was set up previously by the installer or by the user. There is no option to not reinstall the JDK, when the installer detects the JDK installation, because the Java JDK check box is read-only and checked. The checkbox should be read-only and unchecked.

**Comment by JacobAMason** [comment]
This is in App Inventor, I assume?  I did a no-no and didn't extract the Java version detection block in the two installers. Found this and fixed it in the Android Studio version before.

**Comment by dmssargent** [comment]
This was in the Android Studio v1.0.4 installer, not in the App Inventor installer.

**Comment by JacobAMason** [comment]
I said that completely backwards, ha. Yes, fixed in App Inventor during f1cfdb73a9fb9e221bb83d49ac415a3301c7fd90 but not working in Android studio because it's missing the ClearSectionFlag line in the .onInit Section. Should've actually looked at the commit instead of relying on my memory, doh.
