### ISSUE TITLE
Android Support Repository not installed for 2016.1.beta

### ISSUE THREAD

**Issue by emmell620** [JacobAMason/FTCDevSuite#19]
Tried to install the Net Install version of Android Studio Net.2016.1.beta.exe. Got a dependency error on the gradle line that was patched.  Culprit was that the Android Support Repository under Build Tools was not installed.  After installing it, the build succeeded.

**Comment by emmell620** [comment]
Same thing happens with Android Studio Full.2016.1.beta.exe.  Android Support Repository was missing.

**Comment by JacobAMason** [comment]
This was fixed in the new beta. The Support Repo is no longer a dependency.
